blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='post_list'),
    path('post/', PostLV.as_view(), name='post_list'),
    # ?P<slug>는 그룹의 이름을 지정하는 구문입니다. 따라서 나중에 해당 그룹의 이름을 이용해서 원하는 정보를 꺼낼 수 있습니다.
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
    # Tag URL
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete')
]

bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkDV, BookmarkLV, BookmarkCreateView, BookmarkChangeLV, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    # app_urlconf에서는 다른 app들과의 중복을 피하기 위해 템플릿에에서 호출할때
    # app_name:namespace 형식을 사용하여 지정해줘야 합니다.
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # 장고 Auth앱에는 login/logout처럼 url이 정의되어 있어서 그 앞에 url 추가를 원하면 이를 표시해야 합니다.

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done')
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    # User 테이블에서 레코드가 삭제되는 경우 그 레코드에 연결된 bookmark 테이블의 레코드도 같이 삭제된다.
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True) 

    def __str__(self):
        return self.title

bookmark/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from bookmark.models import Bookmark
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

# Create your views here.
class BookmarkLV(ListView):
    # object_list을 컨텍스트 변수로 사용
    model = Bookmark

    # 만약 ListView가 자동으로 bookmark_list.html 파일을 rendering하지 못할때 명시적으로 지정
    # template_name = 'bookmark/bookmark_list.html'


class BookmarkDV(DetailView):
    # object를 컨텍스트 변수로 사용
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}

{% block title %}bookmark_change_llst.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Bookmark Change - {{user}}</h1>
<br>

<table class="table table-dark border-primary">
    <thread>
        <tr class="table-info">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thread>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:delete' item.id  %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Bookmark Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}
<div style="padding-top: 20px; padding-bottom: 20px;">
    <h3 style="color:#09ff00">{{object.title}}:&nbsp;&nbsp;&nbsp;
        <a href="{{object.url}}">{{object.url}}</a></h3>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-md-end" style="padding-bottom: 20px;">
    <a class="btn btn-info" href="{% url 'bookmark:index' %}" role="button">뒤로가기</a>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Bookmark Create/Update - {{ user }}</h1>
<p class="fst-italic">This is a creation or update form for your bookmark.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="fw-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" class="card pt-3" style="color:black">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.url|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
        <div class="col-sm-5">
            {{ form.url|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group mt-3">
        <div class="col-sm-1 offset-sm-3">
            <button type="'submit" value="Submit" class="btn btn-info">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}
<div style="padding-top: 20px; padding-bottom: 20px;">
    <h1 style="color:#09ff00">Bookmark List</h1>
    <br>

    <ul>
        {% for bookmark in object_list %}
        <li style="color:#51c8ff">{{bookmark.title}}:&nbsp;&nbsp;&nbsp;
            <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.url}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}