blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='post_list'),
    path('post/', PostLV.as_view(), name='post_list'),
    # ?P<slug>는 그룹의 이름을 지정하는 구문입니다. 따라서 나중에 해당 그룹의 이름을 이용해서 원하는 정보를 꺼낼 수 있습니다.
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
    # Tag URL
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # 장고 Auth앱에는 login/logout처럼 url이 정의되어 있어서 그 앞에 url 추가를 원하면 이를 표시해야 합니다.

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done')
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')

    # auto_now_add는 객체가 생성되면 자동으로 시각을 저장
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)

    # auto_now는 객체가 데이터베이스에 저장될 때의 시각을 자동으로 저장. 즉, 객체가 변경될때 저장
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='OWNER')

    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        # admin page에서 보여주는 복수형 글자
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        # 해당 메서드가 실행되면 url 패턴 이름을 기반으로 url를 동적으로 생성합니다.
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    
    def get_next(self):
        return self.get_next_by_modify_dt()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post
from django.conf import settings
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render


# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html' # 지정 안하면 model명_list.html를 찾아 rendering 시도

    '''
    기존 context변수명인 object_list 이름을 posts로 변경이 가능!
    지정해주더라도 기존 object_list이름도 사용 가능!
    '''
    context_object_name = 'posts'
    paginate_by = 2 # 한 페이지에 보여줄 객체 리스트 개수를 제공

class PostDV(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    context_object_name = 'random_parameter'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self) -> QuerySet[Any]:
        # Django ORM에서 __name (더블 언더스코어)는 Post model과 연결된 Tag 모델의 이름을 나타낸다.
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    
    # To add context variable in templates file, override get_context_data()
    def get_context_data(self, **kwargs):
        # 상위 클래스에서 바뀌기 전 context variable를 가져옵니다.
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag'] # url에서 해시값으로 전달될 <str:'
        return context

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        print('method executed')
        context = super().get_context_data(**kwargs)
        # 폼을 my_form으로 설정
        context['my_form'] = context.get('form', self.get_form())
        print('++++++++++++', context)
        return context

    # def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
    #     print('method executed wrong')
    #     context = super().get_context_data(**kwargs)
    #     if 'myy_form' not in context:  # 만약 my_form이 없으면, 새로운 폼 객체 생성
    #         context['myy_form'] = self.get_form()
    #     context['myy_form'] = context.get('form')  # 기존 폼을 가져와서 my_form에 할당
    #     print('+++++++++++',context)
    #     return context
    
    def form_valid(self, form: Any) -> HttpResponse:
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(
            Q(title__icontains=searchWord) |
            Q(description__icontains=searchWord) |
            Q(content__icontains=searchWord)
        ).distinct()

        context = {
            'my_form': form,  # my_form으로 설정
            'search_term': searchWord,
            'object_list': post_list,
        }
        return render(self.request, self.template_name, context)
    
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    initial = {'slug': 'auto-filling-do-not-input'}
    # fields = ['title', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        # self.request.user : 현재 로그인한 유저
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:post_list')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Blog List</h1>
<br>

{% for post in posts %}
    <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>

    <!-- | <- 이 기호는 템플릿에서 필터를 적용하는 데 사용 -->
    {{post.modify_dt|date:"N d, Y"}}
    <p>{{post.description}}</p>
{% endfor %}
<br>
<div style="padding-bottom: 20px;">
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %}
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">NextPage</a>
        {% endif %}
    </span>
</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Archives until {% now "N d, Y" %}</h1>
{% for date in date_list %}
    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}" class="btn btn-outline-info btn-sm mx-1">Year{{date|date:'Y'}}</a>
{% endfor %}
<br><br>

<div style="padding-bottom: 20px;">
    <ul>
        {% for post in object_list %}
        <li class="h5">{{post.modify_dt|date:'Y-m-d'}}&nbsp;:&emsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Archives for {{ day|date:'N d Y' }}</h1>
<br>
<div style="padding-bottom: 10px;">
    <ul>
        {% for post in object_list %}
        <li>{{post.modify_dt|date:'Y-m-d'}}&nbsp;:&emsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Archives for {{ month|date:'N Y' }}</h1>
<br><br>
<div style="padding-bottom: 20px;">
    <ul>
        {% for post in random_parameter %}
        <li class="h5">{{ post.modify_dt|date:'Y-m-d' }}&nbsp;:&emsp;
            <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Archives for {{ year|date:'Y'}}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}" class="btn btn-outline-info btn-sm mx-1">
            {{date|date:'F'}}
        </a>
    </li>
    {% endfor %}
</ul>
<br>

<div style="padding-bottom: 10px;">
    <ul>
        {% for post in object_list %}
        <li class="h5">{{ post.modify_dt|date:'Y-m-d'}}&nbsp;:&emsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Change - {{user}}</h1>
<br>

<table class="table table-dark border-primary">
    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}post_detail.html{% endblock %}

{% block extra-style %}
<style>
.post-body {
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px; 
}
</style>
{% endblock extra-style %}

{% block content %}
<div class="post-body">
    <h2 style="color:#09ff00">{{object.title}}</h2>

    <p>
        {% if object.get_previous %}
        <!-- title은 커서를 갖다 놓았을때 뜨는 문구를 설정할 수 있다. -->
        <a href="{{object.get_previous.get_absolute_url}}" title="View previous post">
            <i class="fas fa-arrow-circle-left"></i> {{ object.get_previous}}
        </a>
        {% endif %}

        {% if object.get_next %}
    |    <a href="{{object.get_next.get_absolute_url}}" title="View Next post">
        {{object.get_next}} <i class="fas fa-arrow-circle-right"></i>
        </a>
        {% endif %}
    </p>

    <br>

    <!-- https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#date -->
    <p>{{object.modify_dt|date:"j F Y"}}</p>
    <br>

    <div style="padding-bottom: 5px;">
        {{object.content|linebreaks}}
    </div>
    <br>
    <div style="padding-bottom: 10px;">
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object post as "tags" %}
        {% for tag in tags %}
            <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        &nbsp;
        <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
    </div>
    <br>
    <div id="disqus_thread"></div>
</div>
{% endblock %}

{% block extra-script %}
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */

    var disqus_config = function () {
        this.page.url = '{{ disqus_url }}';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '{{disqus_id}}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.title = '{{ disqus_title}}';
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" 
    rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Post Create/Update - {{user}}</h1>
<p class="fst-italic">This is a creation or update from for your post.</p>

{% if form.errors %}
<div clas="alert alert-danger">
    <div class="fw-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" class="card pt-3" style="color:black">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:'autofocus' }}
        </div>
    </div>

    <div class="form-group row mt-3">
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.slug|add_class:"form-control"|attr:"readonly"}}
        </div>
        <div class="col">
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>
    </div>

    <div class="form-group row mt-3">
        {{ form.description|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control" }}
        </div>
        <div class="col"> 
            <small class="form-text text-muted">{{ form.description.help_text }}</small>
        </div>
    </div>

    <div class="form-group row mt-3">
        {{ form.content|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
        <div class="col-sm-8">
            {{ form.content|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group row mt-3">
        {{ form.tags|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.tags|add_class:'form-control' }}
        </div>
        <div class="col">
            <small class="form-text text-muted">{{ form.tags.help_text }}</small>
        </div>
    </div>

    <div class="form-group row mt-3">
        <div class="col-sm-1 offset-sm-5">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>
    </div>

</form>
{% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}

{% block title %}post_search.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Blog Search</h1>
<br>

<form action="." method="post">{% csrf_token %}
    {{ my_form.as_table }}
    <input type="submit" value="Submit" class="btn btn-outline-info btn-sm">
</form>

<br/><br/>

{% if object_list %}
{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_dt|date:"N d Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

{% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}
{% endblock %}