blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='post_list'),
    path('post/', PostLV.as_view(), name='post_list'),
    # ?P<slug>는 그룹의 이름을 지정하는 구문입니다. 따라서 나중에 해당 그룹의 이름을 이용해서 원하는 정보를 꺼낼 수 있습니다.
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
    # Tag URL
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # 장고 Auth앱에는 login/logout처럼 url이 정의되어 있어서 그 앞에 url 추가를 원하면 이를 표시해야 합니다.

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done')
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from photo import views
from photo.views import AlbumLV, AlbumDV, PhotoDV, AlbumPhotoCV, AlbumChangeLV, AlbumPhotoUV, AlbumDelV, PhotoCV, PhotoChangeLV, PhotoUV, PhotoDelV

app_name = 'photo'

urlpatterns = [
    path('', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),
    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDelV.as_view(), name='photo_delete')
]

photo/models.py
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER',
                              blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('upload_Date', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='OWNER',
                              blank=True, null=True)

    class Meta:
        ordering = ('title',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from django.forms import inlineformset_factory
from photo.models import Album, Photo

PhotoInlineFormSet = inlineformset_factory(
    Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2
    )

photo/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from mysite.views import OwnerOnlyMixin
from photo.forms import PhotoInlineFormSet
from django.shortcuts import redirect
from django.urls import reverse_lazy
from photo.models import Album, Photo

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:album_list')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:album_list')

class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:album_list')

class AlbumChangeLV(LoginRequiredMixin, ListView):
    model = Album
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:album_list')

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:album_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            # redirect는 httpresponseredirect처럼 명시적으로 지정할 필요가 없기 때문에 더 유연하게 처리 가능!
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:album_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Album Change - {{user}}</h1>

<table class="table table-dark border-primary">
    <thead>
        <tr class="table-success">
            <th>Name</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{item.name}}</td>
            <td>{{item.description}}</td>
            <td>{{item.owner}}</td>
            <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Album Delete <small class="fst-italic">(including related photos)</small></h1>
<br>
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"</p>
    <input type="submit" value="Confirm" class="btn btn-info btn-sm"/>
</form>
{% endblock %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% block title %}album_detail.html{% endblock %}

{% block extra-style %}
<style>
.thumbnail {
    border: 5px solid #09ff00;    
}
</style>
{% endblock %}

{% block content %}
<div class="mt-5">
    <span class="h2">{{ object.name }}&emsp;</span>
    <span class="h5 fst-italic">{{ object.description }}</span>
</div>

<hr style="margin: 0 0 20px 0;">

<div class="row">
    {% for photo in object.photo_set.all %}
    <div class="col-md-3 mb-5">
        <div class="thumbnail">
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" style="width: 100%">
            </a>
        </div>
    <ul>
        <li class="fst-italic">{{ photo.title }}</li>
        <li class="fst-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
    </ul>
    </div>
    {% endfor %}
</div>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a type="button" class="btn btn-info mx-3" href="{% url 'photo:album_list' %}">Back</a>
</div>

{% endblock %}

photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}album_form.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Album-Photo Create/Update - {{user}}</h1>
<p class="fst-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>
{% if form.errors %}
<div class="alert alert-danger">
    <div class="fw-bold">Wrong! Please correct the form error(s) below.</div>
    {{form.errors}}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="fw-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
        {{formerrors}}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
{% else %}
<form action="." method="post">
{% endif %}
{% csrf_token %}
<h4 style="color:#51c8ff">create or update album contents</h4>
<fieldset class="card pt-3" style="color:black">
    <div class="form-group row">
        {{form.name|add_label_class:"col-form-label col-sm-3 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{form.name|add_class:"form-control"|attr:"autofocus"}}
        </div>
    </div>

    <div class="form-group row mt-3">
        {{form.description|add_label_class:"col-form-label col-sm-3 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control" }}
        </div>
    </div>
</fieldset>
<br>

<h4 style="color:#51c8ff">Create or Update photo contents</h4>

<fieldset class="card pt-3" style="color:black">
    <!-- Formset에 들어 있는 각 Form을 다루는 경우 해당 변수를 반드시 추가해야 합니다. -->
    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
        <!-- 주석처리된 템플릿 언어 -->
        {# form.album #}
    <div class="form-group row">
        {{ form.image|add_label_class:"col-form-label col-sm-3 ms-2 fw-bold"}}
        <div class="col-sm-5">
            {{ form.image|add_class:"form-control-file" }}
        </div>
    </div>
    <div class="form-group row mt-2">
        {{ form.title|add_label_class:"col-form-label col-sm-3 ms-2 fw-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control" }}
        </div>
    </div>
    <div class="form-group row mt-2">
        {{ form.description|add_label_class:"col-form-label col-sm-3 ms-2 fw-bold" }}
        <div class="col-sm-8">
            {{ form.description|add_class:"form-control"|attr:"rows:3" }}
        </div>
    </div>

    <hr>
    {% endfor %}
</fieldset>

    <div class="form-group card py-1">
        <div class="col-sm-5 offset-sm-3">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>

    </div>
</form>
{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %}album_list.html{% endblock %}

{% block extra-style %}
<style>
.thumbnail {
    border: 3px solid #09ff00;
}
</style>
{% endblock %}

{% block content %}
    {% for item in object_list %}
        <div class="mt-5">
            <a class="h2" href="{{ item.get_absolute_url }}">{{ item.name }}
            </a>&emsp;
            <span class="fst-italic h5">{{ item.description }}</span>
        </div>
        <!-- 수평줄을 그리고 하단 여백을 20px로 줍니다. -->
        <hr style="margin: 0 0 20px 0;">
        <div class="container text-center">
            <div class="row">
                {% for photo in item.photo_set.all|slice:":5" %}
                <div class="col mx-3">
                    <div class="thumbnail">
                        <a href="{{ photo.get_absolute_url }}">
                            <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Photo Change - {{user}}</h1>
<table class="table table-dark border-primary">
    <thead>
        <tr class="table-info">
            <th>Album</th>
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.album }}</td>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}photo_confirm_delete.html{% endblock %}]

{% block content %}
<h1 style="color:#09ff00">Photo Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delet "{{object}}"</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}photo_detail.html{% endblock %}

{% block content %}
<h2 class="mt-5" style="color:#09ff00">{{ object.title }}</h2>

<div class="row">
    <div class="col-md-9">
        <a href="{{object.image.url}}">
            <img src="{{object.image.url}}" style="width: 100%;">
        </a>
    </div>

    <ul class="col-md-3 mt-3">
        <li class="h5">Photo Description</li>
            {% if object.description %}<p>{{ object.description|linebreaks}}</p>
            {% else %}<p>(blank)</p>{% endif %}
        <li class="h5">Date Uploaded</li>
            <p class="fst-italic">{{object.upload_dt}}</p>
        <li class="h5">Album Name</li>
            <p class="fst-italic">
                <a href="{{ object.album.get_absolute_url }}">
                    {{object.album.name}}
                </a>
            </p>
    </ul>
</div>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}photo_form.html{% endblock %}

{% block content %}
<h1 style="color:#09ff00">Photo Create/Update - {{user}}</h1>
<p class="fst-italic">This is a creation or update form for your photo.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="fw-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
<form enctype="multipart/form-data" action="" method="post" class="card pt-3" style="color:black">
{% else %}
<form action="." method="post" class="card pt-3">
{% endif %}
{% csrf_token %}
<div class="form-group row">
    {{ form.album|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
    <div class="col-sm-2">
        {{ form.album|add_class:"form-control" }}
    </div>
    <div class="col-sm-4 my-auto">
        <a href="{% url 'photo:album_add' %}" class="btn btn-info">Add Album</a>
    </div>
</div>

<div class="form-group row mt-2">
    {{ form.title|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
    <div class="col-sm-5">
        {{ form.title|add_class:"form-control"|attr:"autofocus" }}
    </div>
</div>

<div class="form-group row mt-2">
    {{ form.image|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
    <div class="col-sm-5">
        {{ form.image|add_class:"form-control-file" }}
    </div>
</div>

<div class="form-group row mt-2">
    {{ form.description|add_label_class:"col-form-label col-sm-2 ms-2 fw-bold" }}
    <div class="col-sm-5">
        {{ form.description|add_class:"form-control"|attr:"rows:3" }}
    </div>
</div>

<div class="form-group mt-2">
    <div class="col-sm-1 offset-sm-5">
        <input type="submit" value="Submit" class="btn btn-info"/>
    </div>
</div>

</form>
{% endblock %}