blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostLV.as_view(), name='post_list'),
    path('post/', PostLV.as_view(), name='post_list'),
    # ?P<slug>는 그룹의 이름을 지정하는 구문입니다. 따라서 나중에 해당 그룹의 이름을 이용해서 원하는 정보를 꺼낼 수 있습니다.
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
    # Tag URL
    path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete')
]

bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkDV, BookmarkLV, BookmarkCreateView, BookmarkChangeLV, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    # app_urlconf에서는 다른 app들과의 중복을 피하기 위해 템플릿에에서 호출할때
    # app_name:namespace 형식을 사용하여 지정해줘야 합니다.
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # 장고 Auth앱에는 login/logout처럼 url이 정의되어 있어서 그 앞에 url 추가를 원하면 이를 표시해야 합니다.

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done')
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from photo import views
from photo.views import AlbumLV, AlbumDV, PhotoDV, AlbumPhotoCV, AlbumChangeLV, AlbumPhotoUV, AlbumDelV, PhotoCV, PhotoChangeLV, PhotoUV, PhotoDelV

app_name = 'photo'

urlpatterns = [
    path('', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),
    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDelV.as_view(), name='album_delete'),
    path('photo/add/', PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDelV.as_view(), name='photo_delete')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <!-- 인터넷 익스플로러(IE)에서 호환성 모드 없이 최신 렌더링 엔진를 사용 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- 모바일 기기에서 어떻게 표시될지 정의 -->
        <meta name="viewport" content="'width=device-width, initial-scale=1">
        <!-- block endblock 구문을 사용하여 하위 상속 파일들이 수정할 가능성이 있는 부분에 삽입! -->
        <title>{% block title %}Django Web Programming{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block extra-style %}{% endblock %}
    </head>
    <body style="padding-top:90px">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container-fluid"> 
              <span class="navbar-brand mx-5 mb-0 fw-bold fst-italic">Django - Python Web Programming</span>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item mx-1 btn">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item mx-1 btn">
                    <a class="nav-link active" aria-current="page" href="{% url 'bookmark:index' %}">Bookmark</a>
                  </li>
                  <li class="nav-item mx-1 btn">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Blog</a>
                  </li>
                  <li class="nav-item mx-1 btn">
                    <a class="nav-link active" href="{% url 'photo:album_list' %}">Photo</a>
                  </li>
                  <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Add
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:add' %}">Post</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
                      <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Change
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:change' %}">Post</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a></li>
                      <li><a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Util
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                    </ul>
                  </li>
                  <form class="from-inline my-2" action="" method="post"> {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria_label="search_word">
                  </form> 
                </ul>
                <ul class="navbar-nav mr-5">
                  <div class="btn-group">
                    <!-- if문을 사용해서 사용자의 로그인 여부를 확인 -->
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <ul class="dropdown-menu">
                      <li><form action="{% url 'logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item">Logout</button></form></li>
                      <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                    </ul>
                    {% else %}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                      <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                    </ul>
                    {% endif %}
                  </div>
                </ul>
              </div>
            </div>
        </nav>
        <div class="container bg-dark text-light" style="padding-bottom: 20px;">
            {% block content %}{% endblock %}
        </div>

        {% block footer %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/b572e80bf8.js" crossorigin="anonymous"></script>

        {% block extra-script %}{% endblock %}
    </body>
</html>

templates/home.html
<!-- base.html로부터 상속을 받아옴! 항상 가장 위에서 삽입 -->
{% extends 'base.html' %}

<!-- 추후 static 파일을 사용시 미리 load 해주어야 함 -->
{% load static %}

<!-- 북마크 이름설정, 검색엔진이 페이지를 인덱싱할때 사용 -->
{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/tf_lockdown.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #000000;
    border-bottom: 10px solid #000000;
    padding: 20px 0 0 20px;
}
.title {
  color: #09ff00;
  font-weight: bold;
}
.powered {
  position: relative;
  top: 84%;
  color: #09ff00;
  font-style: italic;
}
</style>
{% endblock %}

{% block content %}
  <div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <!-- <i> 태그는 폰트어썸의 아이콘을 사용할때 사용. 이름및 사용법은 폰트어썸 홈페이지에서 확인 -->
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap</h4>
  </div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6" style="color:#09ff00">
      <h3>Bookmark App</h3>
      <p style="color:#51c8ff">
        Bookmark is a Uniform Resource Identifier (URI)
        that is stored for later retrieval in any of various storage formats.
        You can store your own bookmarks by Bookmark application.
        It's also possible to update or delete your bookmarks.
      </p>
    </div>
    <!-- bootstrap은 총 12컬럼을 가지고 있다. -->
    <div class="col-sm-6" style="color:#09ff00">
      <h3>Blog App</h3>
      <p style="color:#51c8ff">
        This application makes it possible to log daily events or write your own interests
        such as hobbies, techniques, etc.
        A typical blog combines text, digital images, and links to other blogs, web pages,
        and other media related to its topic.
      </p>
    </div>
  </div>
  {% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-dark">
  <div class="text-white fst-italic text-end me-3">
    Copyright &copy: IanDLog by Ian
  </div> 
</footer>
{% endblock %}